package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.BaseInfoCompanyPermit;

public interface BaseInfoCompanyPermitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_permit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_permit
     *
     * @mbggenerated
     */
    int insert(BaseInfoCompanyPermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_permit
     *
     * @mbggenerated
     */
    int insertSelective(BaseInfoCompanyPermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_permit
     *
     * @mbggenerated
     */
    BaseInfoCompanyPermit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_permit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseInfoCompanyPermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_permit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseInfoCompanyPermit record);
}