package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.BaseInfoCompanyPay;

public interface BaseInfoCompanyPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_pay
     *
     * @mbggenerated
     */
    int insert(BaseInfoCompanyPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_pay
     *
     * @mbggenerated
     */
    int insertSelective(BaseInfoCompanyPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_pay
     *
     * @mbggenerated
     */
    BaseInfoCompanyPay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseInfoCompanyPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseInfoCompanyPay record);
}