package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.BaseInfoCompanyService;

public interface BaseInfoCompanyServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_service
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_service
     *
     * @mbggenerated
     */
    int insert(BaseInfoCompanyService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_service
     *
     * @mbggenerated
     */
    int insertSelective(BaseInfoCompanyService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_service
     *
     * @mbggenerated
     */
    BaseInfoCompanyService selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseInfoCompanyService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_base_info_company_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseInfoCompanyService record);
}