package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.CarScreenDriver;

public interface CarScreenDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_screen_driver
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_screen_driver
     *
     * @mbggenerated
     */
    int insert(CarScreenDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_screen_driver
     *
     * @mbggenerated
     */
    int insertSelective(CarScreenDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_screen_driver
     *
     * @mbggenerated
     */
    CarScreenDriver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_screen_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarScreenDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_screen_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarScreenDriver record);
}