package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.ChargeRule;

public interface ChargeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int insert(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int insertSelective(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    ChargeRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChargeRule record);
}