package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.ChargeRuleDetail;

public interface ChargeRuleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule_detail
     *
     * @mbggenerated
     */
    int insert(ChargeRuleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule_detail
     *
     * @mbggenerated
     */
    int insertSelective(ChargeRuleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule_detail
     *
     * @mbggenerated
     */
    ChargeRuleDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChargeRuleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChargeRuleDetail record);
}