package com.lkmotion.yesincar.mapper;

public interface CheckRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_check_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_check_record
     *
     * @mbggenerated
     */
    int insert(CheckRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_check_record
     *
     * @mbggenerated
     */
    int insertSelective(CheckRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_check_record
     *
     * @mbggenerated
     */
    CheckRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_check_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_check_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckRecord record);
}
