package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.DriverBaseInfo;

public interface DriverBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_base_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_base_info
     *
     * @mbggenerated
     */
    int insert(DriverBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_base_info
     *
     * @mbggenerated
     */
    int insertSelective(DriverBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_base_info
     *
     * @mbggenerated
     */
    DriverBaseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_base_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DriverBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_base_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DriverBaseInfo record);
}