package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.DriverIncomeDetail;

public interface DriverIncomeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_income_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_income_detail
     *
     * @mbggenerated
     */
    int insert(DriverIncomeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_income_detail
     *
     * @mbggenerated
     */
    int insertSelective(DriverIncomeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_income_detail
     *
     * @mbggenerated
     */
    DriverIncomeDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_income_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DriverIncomeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_income_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DriverIncomeDetail record);
}
