package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.DynamicDiscountRule;

public interface DynamicDiscountRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int insert(DynamicDiscountRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int insertSelective(DynamicDiscountRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    DynamicDiscountRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DynamicDiscountRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DynamicDiscountRule record);
}