package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.EvaluateDriver;

public interface EvaluateDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_evaluate_driver
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_evaluate_driver
     *
     * @mbggenerated
     */
    int insert(EvaluateDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_evaluate_driver
     *
     * @mbggenerated
     */
    int insertSelective(EvaluateDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_evaluate_driver
     *
     * @mbggenerated
     */
    EvaluateDriver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_evaluate_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EvaluateDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_evaluate_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EvaluateDriver record);
}