package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.OrderRulePrice;

public interface OrderRulePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int insert(OrderRulePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int insertSelective(OrderRulePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    OrderRulePrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRulePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRulePrice record);
}