package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.OrderRulePriceDetail;

public interface OrderRulePriceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int insert(OrderRulePriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderRulePriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    OrderRulePriceDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRulePriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRulePriceDetail record);
}