package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.OrderReassignmentRecord;

public interface OrderReassignmentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_reassignment_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_reassignment_record
     *
     * @mbggenerated
     */
    int insert(OrderReassignmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_reassignment_record
     *
     * @mbggenerated
     */
    int insertSelective(OrderReassignmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_reassignment_record
     *
     * @mbggenerated
     */
    OrderReassignmentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_reassignment_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderReassignmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_reassignment_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderReassignmentRecord record);
}