package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.PassengerStatics;

public interface PassengerStaticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_statics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_statics
     *
     * @mbggenerated
     */
    int insert(PassengerStatics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_statics
     *
     * @mbggenerated
     */
    int insertSelective(PassengerStatics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_statics
     *
     * @mbggenerated
     */
    PassengerStatics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_statics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PassengerStatics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_statics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PassengerStatics record);
}