package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.PassengerMessage;

public interface PassengerMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_message
     *
     * @mbggenerated
     */
    int insert(PassengerMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_message
     *
     * @mbggenerated
     */
    int insertSelective(PassengerMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_message
     *
     * @mbggenerated
     */
    PassengerMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PassengerMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PassengerMessage record);
}
