package com.lkmotion.yesincar.mapper;

import com.lkmotion.yesincar.entity.PassengerAddress;

public interface PassengerAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbggenerated
     */
    int insert(PassengerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbggenerated
     */
    int insertSelective(PassengerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbggenerated
     */
    PassengerAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PassengerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PassengerAddress record);
}
