package com.lkmotion.yesincar.request;

import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

/**
 * 订单
 * @author LiHeng

 **/
@EqualsAndHashCode(callSuper = true)
@Data
public class OrderRequest extends AbstractRequest {
    private String orderPrice;
    /**
     * 城市编码
     */
    private String cityCode;
    private String cityName;

    private Integer serviceTypeId;
    private String serviceTypeName;

    private Integer channelId;
    private String channelName;

    private Integer carLevelId;
    private String carLevelName;

    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_number
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_info_id
     *
     * @mbggenerated
     */
    private Integer passengerInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_phone
     *
     * @mbggenerated
     */
    private String passengerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.device_code
     *
     * @mbggenerated
     */
    private String deviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_id
     *
     * @mbggenerated
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_status
     *
     * @mbggenerated
     */
    private Integer driverStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_phone
     *
     * @mbggenerated
     */
    private String driverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.user_longitude
     *
     * @mbggenerated
     */
    private String userLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.user_latitude
     *
     * @mbggenerated
     */
    private String userLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_longitude
     *
     * @mbggenerated
     */
    private String startLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_latitude
     *
     * @mbggenerated
     */
    private String startLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_address
     *
     * @mbggenerated
     */
    private String startAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.end_address
     *
     * @mbggenerated
     */
    private String endAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_start_time
     *
     * @mbggenerated
     */
    private Date orderStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.end_longitude
     *
     * @mbggenerated
     */
    private String endLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.end_latitude
     *
     * @mbggenerated
     */
    private String endLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_grab_time
     *
     * @mbggenerated
     */
    private Date driverGrabTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_start_time
     *
     * @mbggenerated
     */
    private Date driverStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_arrived_time
     *
     * @mbggenerated
     */
    private Date driverArrivedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_time
     *
     * @mbggenerated
     */
    private Date receivePassengerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_longitude
     *
     * @mbggenerated
     */
    private String receivePassengerLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_latitude
     *
     * @mbggenerated
     */
    private String receivePassengerLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_time
     *
     * @mbggenerated
     */
    private Date passengerGetoffTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_longitude
     *
     * @mbggenerated
     */
    private String passengerGetoffLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_latitude
     *
     * @mbggenerated
     */
    private String passengerGetoffLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.other_name
     *
     * @mbggenerated
     */
    private String otherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.other_phone
     *
     * @mbggenerated
     */
    private String otherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_type
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.service_type
     *
     * @mbggenerated
     */
    private Integer serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_channel
     *
     * @mbggenerated
     */
    private Integer orderChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.transaction_id
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.mapping_id
     *
     * @mbggenerated
     */
    private String mappingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.mapping_number
     *
     * @mbggenerated
     */
    private String mappingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.merchant_id
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_evaluate
     *
     * @mbggenerated
     */
    private Integer isEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.invoice_type
     *
     * @mbggenerated
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_annotate
     *
     * @mbggenerated
     */
    private Integer isAnnotate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.use_coupon
     *
     * @mbggenerated
     */
    private Integer useCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.cancel_order_type
     *
     * @mbggenerated
     */
    private Integer cancelOrderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_paid
     *
     * @mbggenerated
     */
    private Integer isPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_cancel
     *
     * @mbggenerated
     */
    private Integer isCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_adjust
     *
     * @mbggenerated
     */
    private Integer isAdjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_dissent
     *
     * @mbggenerated
     */
    private Integer isDissent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_manual
     *
     * @mbggenerated
     */
    private Integer isManual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_following
     *
     * @mbggenerated
     */
    private Integer isFollowing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_fake_success
     *
     * @mbggenerated
     */
    private Integer isFakeSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * 过路费
     */
    private Double roadPrice;
    /**
     * 停车费
     */
    private Double parkingPrice;
    /**
     * 其它费用
     */
    private Double otherPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.driver_id_now
     *
     * @mbggenerated
     */
    private Integer driverIdNow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.operator
     *
     * @mbggenerated
     * 操作者
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.reason_type
     *
     * @mbggenerated
     * 改派类型
     */
    private Integer reasonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.reason_text
     *
     * @mbggenerated
     * 改派内容
     */
    private String reasonText;

}
