#common 通用
server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://drdshbga87913c27public.drds.aliyuncs.com/lkmotion?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: lkmotion
    password: yVp_2vPxykz6m1S
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,slf4j
      initialSize: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'
  activemq:
    broker-url: tcp://192.168.33.239:61617
    in-memory: false
    pool:
      enabled: true
      max-connections: 100


#internal 程序内部
logging:
  config: classpath:log/logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#customer

#支付宝微信回调地址（昌磊注意）
callback: http://16f11p5264.51mypc.cn:11964
#支付宝
alipay:
  #商户秘钥
  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCDsXW9KQ9U1fbD+kR2sBHnYKaDXS1X0O5Q+L26jGqs7NS51n7Crh6O4nQG0SABO8QpGYJ21G2AhhUmU3C5VYD0HsQ7KyyEZPHjEIL2hVFOAyc5xkH3fJdCRBtzwuGNQZgf0yTgFGPOSvHbi1v0XyM5GLARO4Cdxz/WKeg1BtvOjKvC/DwGWRnz/uk7n8VQPLLXujET2rx/5l0tS627klqW9obtb1OoOE77GutFzcH510B6s+47nu8tQdfcmFBQ2MsDCT+gsPphUj527fpKUpnQ6hSxi2ubuldV66PPsvok/Qsza30OF4rVn8YBopcKEPsjpk54kfAjjJtOc8lyg4SHAgMBAAECggEAPAvcPWXNYcc1fuJL+ToKz88X3WnM1O+k2jKwf7CqqzJJRHryzV2K/Wdvs/QCfc18gajp/biaPTHlztXY3giIhcbJfpkO8Ub9q6TJshHToph5eDRXu7qJVWOsiLnhEgFIlao2dB2X7GXrpUkDoocGjnAdR54z5L0G9GWjRRpdeu2ngKBCSP8d5gUcnlQScJ8KRySdtyG8J5rqCjqzDGudG8tezuQYg8HZCDufLiWliCuOgU2/GG1oZkdu2PKBiQva/AmUq/CH3xqRnecs2+AB66ulClWqiaLQxHTuW6sIWmh3+5KvyAzykYyplZUWQMx5ZymE0/sTYPTA2eeF6Fk7YQKBgQDwpnDwEEXyrvmrF//ZX5DJG+pKJwE5m29BwBnwL2sEbpmpu0sD3RtKR0p2S5hCH1SmN9GaQjZCSLx2WaPcnDjqaylCcVYKY+Mp2e5YhbZ3xAS0WMc8G6Ni5O4ouOoPhTR3XWs9Y+w4/7d35JAtHq9GVtzvsvk+tDMjNGPB1BjViQKBgQCMF95a1wh0PkLRK9w6GYps5K+zJfHu9m4DEbnx/DjM2bI4hKbYFDimGsRqromy7ofSm5ojiOb/abj/BY5lul6ha7/5/CpdMD/wRJR8cOcP37ea7aNdyRG1V8V6z0okMwsw/Ttz0IJN0msuuMwzJJGlR5QZudOAsDNmH173ziAVjwKBgBZPmBDpsVJ6nnMaWoIQth+vEt2lGBv7KSlzYfQ+sTFL/7sYvi+xhCIy0dh90bPvq61tZ2Vh1h33GGHwlZySb0RsgvrB/zQfZqQurEZQv0YDSlxeDrqn5VH534qu+iROOTsH0jVy2ie+rYfUDPnh6mYfD4S5lxoVItiUttr1iwfhAoGAECzlWJnBeSKDNoGY8QBn8kDJZKb58zxy4VnXnXAg4s4z/MCcPxC+pbcrfKHgdk+CUTf0KSwyd8UuPgvXMDm/mWXGiceq4I2kpEpW1rN2imerXHEZzsdbixOyUobCqcFXBnYGuk2V7gRgqclekn0jb/D+0aWaHR67IIx4u6YKIFMCgYEApLkLVj0LYGBpuxryzoGBLVMKRDUV1DwSYHyEuN8NzqmM+MIZdYftDi2V5YrHFKJ6UWojazRubtU2z3fRiidpLbFPnZAHKSEyTCO57R7E459EMlzEV7dFPcW8NCxzXxR846Gw5QrlO+3kithb8xybtY/AZAUufIoTkQ50lXSEwi4=
  #支付宝公钥
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzPMVfaCrCY6CTKe4zhZbf5aY/ehCgjH2Q4yyw1ItQkgVXqklfma9Fsgr7QQefjlRlxf6trZGqLgh5IdPZSw4omJY+qRMpEW8HUUIAbmQ4BvdWzF4a7to42di4DPeMRIF9I+t6g1X4Jl0dKk986Mx6lLwqrSAZLIzgYKM/YNcoqHvnV1mc1UOtvcpr2srDHwT9O7MczndJI7VzoVwWKcktA/IVpOFXhe+taQandVWGjZ9OLJ5P6sIFE77ltbIcZO2wtTvuE9wTxO43kCfTVu9ALRP6B/ihpBZrxuasYz8q6kCQfvglxld0SPLarp9RqkAPs9OlX5Vbnjw46qiyCPMowIDAQAB
  #商户APPID
  app-id: 2018032002413903
  #商家和支付宝签约的产品码，为固定值QUICK_MSECURITY_PAY
  product-code: QUICK_MSECURITY_PAY
  #支付宝网关地址
  gateway: https://openapi.alipay.com/gateway.do
  #交易关闭时间
  close-trade-time: https://api.mch.weixin.qq.com/pay/orderquery

#微信支付
wxpay:
  appId: wx2cdaec7109a8b705
  mchId: 1504990521
  key: 89glinkq2s2REkIBFqJs4FlnziuCqONQ
  unifiedorder.api: https://api.mch.weixin.qq.com/pay/unifiedorder
  query.api: https://api.mch.weixin.qq.com/pay/orderquery