package com.lkmotion.yesincar.file.entity;

public class PassengerAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.passenger_info_id
     *
     * @mbggenerated
     */
    private Integer passengerInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.address_name
     *
     * @mbggenerated
     */
    private String addressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.address_desc
     *
     * @mbggenerated
     */
    private String addressDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.id
     *
     * @return the value of tbl_passenger_address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.id
     *
     * @param id the value for tbl_passenger_address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.passenger_info_id
     *
     * @return the value of tbl_passenger_address.passenger_info_id
     *
     * @mbggenerated
     */
    public Integer getPassengerInfoId() {
        return passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.passenger_info_id
     *
     * @param passengerInfoId the value for tbl_passenger_address.passenger_info_id
     *
     * @mbggenerated
     */
    public void setPassengerInfoId(Integer passengerInfoId) {
        this.passengerInfoId = passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.latitude
     *
     * @return the value of tbl_passenger_address.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.latitude
     *
     * @param latitude the value for tbl_passenger_address.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.longitude
     *
     * @return the value of tbl_passenger_address.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.longitude
     *
     * @param longitude the value for tbl_passenger_address.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.address_name
     *
     * @return the value of tbl_passenger_address.address_name
     *
     * @mbggenerated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.address_name
     *
     * @param addressName the value for tbl_passenger_address.address_name
     *
     * @mbggenerated
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.type
     *
     * @return the value of tbl_passenger_address.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.type
     *
     * @param type the value for tbl_passenger_address.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.address_desc
     *
     * @return the value of tbl_passenger_address.address_desc
     *
     * @mbggenerated
     */
    public String getAddressDesc() {
        return addressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_address.address_desc
     *
     * @param addressDesc the value for tbl_passenger_address.address_desc
     *
     * @mbggenerated
     */
    public void setAddressDesc(String addressDesc) {
        this.addressDesc = addressDesc == null ? null : addressDesc.trim();
    }
}