#common 通用
server:
  port: 8084

#internal 程序内部
logging:
  config: classpath:log/logback-spring.xml

#customer
#高德地图
amap:
    key: 3c71f0b7e997905e528729e0a0234729
    sid: 3289
#  key: 9fb2066ba4cfbf6f374e09a6b6c6ca0e
#  sid: 2510
